### ISSUE TITLE
Unhandled Error on Pump Control

### ISSUE THREAD

**Issue by MBeuttler** [IUNO-TDM/PumpControl#17]
```
1|PumpCont | [2017-08-07 14:39:38] [frame_header] Dispatching write containing 1 message(s) containing 2 header bytes and 17 payload bytes
1|PumpCont | [2017-08-07 14:39:38] [frame_header] Header Bytes: 
1|PumpCont | [0] (2) 81 11 
1|PumpCont | 
1|PumpCont | 2017-08-07 14:39:38,059 DEBUG [default] [mixer@unknown-host] [void WebInterface::SendMessage(std::string)] [src/webinterface.cpp:128] WebInterface send message: {"progressUpdate":{"orderName":"Detlef Drinker","progress":0}}
1|PumpCont | 2017-08-07 14:39:38,059 INFO  [default] setPump 1 : 0.00157143
1|PumpCont | [2017-08-07 14:39:38] [http] localhost:9002 [::ffff:127.0.0.1]:41630 "PUT /program HTTP/1.1" 200 7 "" 
1|PumpCont | 2017-08-07 14:39:38,129 DEBUG [default] [mixer@unknown-host] [bool WebInterface::Start()] [src/webinterface.cpp:93] Webinterface start on port 9002
1|PumpCont | 2017-08-07 14:39:38,130 ERROR [default] Underlying Transport Error
1|PumpCont | 2017-08-07 14:39:38,130 ERROR [default] Could not inititalize the WebInterface. You can now close the application.
----
1|PumpCont | SyntaxError: Invalid or unexpected token
1|PumpCont |     at createScript (vm.js:74:10)
1|PumpCont |     at Object.runInThisContext (vm.js:116:10)
1|PumpCont |     at Module._compile (module.js:533:28)
1|PumpCont |     at Object.Module._extensions..js (module.js:580:10)
1|PumpCont |     at Module.load (module.js:503:32)
1|PumpCont |     at tryModuleLoad (module.js:466:12)
1|PumpCont |     at Function.Module._load (module.js:458:3)
1|PumpCont |     at /home/mixer/.nvm/versions/node/v8.2.1/lib/node_modules/pm2/lib/ProcessContainer.js:324:23
1|PumpCont |     at /home/mixer/.nvm/versions/node/v8.2.1/lib/node_modules/pm2/node_modules/async/dist/async.js:421:16
1|PumpCont |     at next (/home/mixer/.nvm/versions/node/v8.2.1/lib/node_modules/pm2/node_modules/async/dist/async.js:5302:29)
1|PumpCont | /home/mixer/PumpControl/build/pumpcontrol.out:1
1|PumpCont | (function (exports, require, module, __filename, __dirname) { ELF
1|PumpCont |                                                               ^

```

**Comment by meierha** [comment]
Hi @MBeuttler,
leider kann ich mit dem Issue überhaupt nichts anfangen, denn:
- es fehlt, was gerade gemacht wurde
- es steht nirgendwo, ob mit einer Simulation oder mit der echten Maschine gearbeitet wurde
- es steht nirgendwo, welcher Softwarestand benutzt wurde
- das Log ist widersprüchlich, es findet sich ein Stackdump aus js darin, der ja wohl nict aus der PumpControl stammen kann ???
- wieso unhandeled Exception? Die PumpControl sagt eindeutig "Could not inititalize the WebInterface", vermutlich, da der Listener auf Port 9002 nicht geöffnet werden konnte. Das Programm empfiehlt Neustart. Eine unhandeled Exception sehe ich hier nicht.
Also bitte: so viel Information, dass ich die Situation nachstellen kann, oder, falls sich das erübrigt haben sollte, den Issue schließen.
Gruß
Hans
